import os

if __name__ == '__main__':
    os.system("python ./anhui.py")
    os.system("python ./beijing.py")
    os.system("python ./fujian.py")
    os.system("python ./gansu.py")
    os.system("python ./guangdong.py")
    os.system("python ./guangxi.py")
    os.system("python ./guizhou.py")
    os.system("python ./hainan.py")
    os.system("python ./chongqing.py")
    os.system("python ./hebei.py")
    os.system("python ./heilongjiang.py")
    os.system("python ./henan.py")
    #os.system("python ./hubei.py")
    os.system("python ./hunan.py")
    os.system("python ./jiangxi.py")
    os.system("python ./jilin.py")
    os.system("python ./liaoning.py")
    os.system("python ./neimenggu.py")
    os.system("python ./ningxia.py")
    os.system("python ./shan1xi.py")
    os.system("python ./shan3xi.py")
    os.system("python ./shandong.py")
    os.system("python ./shanghai.py")
    os.system("python ./sichuan.py")
    os.system("python ./tianjin.py")
    os.system("python ./xinjiang.py")
    os.system("python ./xizang.py")
    os.system("python ./yunnan.py")
    os.system("python ./zhejiang.py")
    os.system("python ./jiangsu.py")
    print("---------All Completed !----------")

