import os

if __name__ == '__main__':
    os.system("python ./workers/anhui.py")
    os.system("python ./workers/beijing.py")
    os.system("python ./workers/fujian.py")
    os.system("python ./workers/gansu.py")
    os.system("python ./workers/guangdong.py")
    os.system("python ./workers/guangxi.py")
    os.system("python ./workers/guizhou.py")
    os.system("python ./workers/hainan.py")
    os.system("python ./workers/chongqing.py")
    #os.system("python ./workers/hebei.py")
    os.system("python ./workers/heilongjiang.py")
    os.system("python ./workers/henan.py")
    os.system("python ./workers/hunan.py")
    os.system("python ./workers/jiangxi.py")
    os.system("python ./workers/jilin.py")
    os.system("python ./workers/liaoning.py")
    os.system("python ./workers/neimenggu.py")
    os.system("python ./workers/ningxia.py")
    os.system("python ./workers/shan1xi.py")
    os.system("python ./workers/shan3xi.py")
    os.system("python ./workers/shandong.py")
    #os.system("python ./workers/shanghai.py")
    os.system("python ./workers/sichuan.py")
    os.system("python ./workers/tianjin.py")
    os.system("python ./workers/xinjiang.py")
    os.system("python ./workers/xizang.py")
    os.system("python ./workers/yunnan.py")
    os.system("python ./workers/zhejiang.py")
    os.system("python ./workers/jiangsu.py")
    print("---------All Completed !----------")

